version: '2'
rules:
  # action name can have only lowercase alpha-numeric characters and hyphens
  action_directory_name: lowercase-hyphens

  # action and workflow files should have extension of `.yml` only
  action_file_extensions: ['yml']
  workflow_file_extensions: ['yml']
  action_called_variable_not_in_double_quote: true

  # named-value variable should not be in a double quote
  workflow_called_variable_not_in_double_quote: true

  # latest version of runners should not be used
  workflow_runs_on_not_latest: true

  # action, its inputs and outputs must have `name` and `description` fields
  action_required__name: true 
  action_required__description: true
  action_input_required__description: true
  action_output_required__description: true

  # only local actions can be used
  action_step_action: local-only

  # environment variable in steps should be uppercase alpha-numeric with optional underscore
  action_step_env: uppercase-underscores 
  
  # all called inputs, outputs etc. exist and are defined
  action_called_input_exists: true 
  action_called_step_output_exists: true
  workflow_called_variable_exists_in_file: true
  workflow_called_input_exists: true
warning_only:
  - action_directory_name
  - action_file_extensions
  - workflow_file_extensions
