version: '3'
rules:
  action_file:
    extension: ['yml'] # Action files should have a .yml extension
    directory_name: lowercase-hyphens # Action names must use only lowercase alphanumeric characters and hyphens
    warning_only:
      - directory_name
      - extension

  workflow_file:
    extension: ['yml'] # Workflow files should have a .yml extension
    warning_only:
      - extension

  action_naming:
    step_env: uppercase-underscores # Environment variables in steps must use uppercase alphanumeric characters, optionally including underscores

  action_required_fields: # Actions, along with their inputs and outputs (where applicable), must include both name and description fields
    action: ['name', 'description']
    input: ['description']
    output: ['description']

  called_variables_syntax:
    action_called_variable_not_in_double_quote: true # Named-value variables should not be enclosed in double quotes

  used_actions: # Only local actions should be used
    action_step_action: local-only
    workflow_job_step_action: local-only

  dependencies: # Verify that all referenced inputs, outputs, and similar entities are properly defined
    action_called_input_exists: true 
    action_called_step_output_exists: true    
    workflow_called_variable_exists_in_file: true
    workflow_called_input_exists: true

  versions:
    workflow_runs_on_field_not_latest: true # The use of the latest runner version should be avoided
