version: "2"
linters:
  default: all
  disable:
    - cyclop
    - tagliatelle
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/keenbytes/octo-linter
            - github.com/keenbytes/broccli/v3
            - gopkg.in/yaml.v2
  exclusions:
    generated: disable
    rules:
      - linters:
          - err113
          - exhaustruct
          - funlen
          - varnamelen
        path: _test.go
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines

