site_name: octo-linter
site_url: https://github.com/keenbytes/octo-linter
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: deep purple
    accent: deep orange
nav:
  - Overview: index.md
  - Demo: demo.md
  - Getting started:
    - Configuration: configuration.md
    - Building: building.md
    - Running locally: running-locally.md
    - GitHub Actions Workflow: github-actions-workflow.md
  - Rules:
    - filenames: rules/filenames.md
    - naming_conventions: rules/naming_conventions.md
    - required_fields: rules/required_fields.md
    - referenced_variables_*: rules/referenced_variables.md
    - used_actions_*: rules/used_actions.md
    - dependencies: rules/dependencies.md
    - workflow_runners: rules/workflow_runners.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/keenbytes/octo-linter

copyright: Copyright &copy; 2024-2025 Mikołaj Gąsior
