site_name: octo-linter
site_url: https://github.com/keenbytes/octo-linter
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: deep purple
    accent: deep orange
nav:
  - Overview: index.md
  - Demo: demo.md
  - Getting started:
    - Configuration: configuration.md
    - Building: building.md
    - Running locally: running-locally.md
    - GitHub Actions Workflow: github-actions-workflow.md
  - All rules: all-rules.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/keenbytes/octo-linter

copyright: Copyright &copy; 2024-2025 Mikolaj Gasior
