// Package main contains octo-linter command.
package main

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"regexp"

	"github.com/spf13/cobra"
	"octo-linter/internal/dotgithub"
	"octo-linter/internal/linter"
	"octo-linter/internal/loglevel"
)

//go:generate go run ../../gen.go ../../

const configFileName = "dotgithub.yml"

// exit codes.
const (
	ExitOK                       = 0
	ExitLintErrors               = 1
	ExitLintOnlyWarnings         = 2
	ExitErrLinting               = 10
	ExitErrReadingDotGithubDir   = 20
	ExitErrGettingCfgFile        = 30
	ExitErrReadingCfgFile        = 31
	ExitErrReadingDefaultCfgFile = 32
	ExitErrReadingVarsFile       = 41
	ExitErrReadingSecretsFile    = 42
	ExitErrCheckingDstPath       = 50
	ExitDstFileIsDir             = 51
	ExitErrWritingCfg            = 52
)

const (
	// FileModeDefaultConfig sets the mode for the config file generated by the 'init' command.
	FileModeDefaultConfig = 0o600
)

var (
	errCfgFileGet               = errors.New("error getting cfg file")
	errCfgFilePopulate          = errors.New("error populating config from file")
	errCfgFileRead              = errors.New("error reading cfg file")
	errDefaultCfgFileRead       = errors.New("error reading default cfg file")
	errDotGithubDirRead         = errors.New("error reading .github directory")
	errDotGithubVarsFileRead    = errors.New("error reading vars file")
	errDotGithubSecretsFileRead = errors.New("error reading secrets file")
)

func errGettingCfgFile(err error) error {
	return fmt.Errorf("%w: %s", errCfgFileGet, err.Error())
}

func errPopulatingCfgFile(err error) error {
	return fmt.Errorf("%w: %s", errCfgFilePopulate, err.Error())
}

func errReadingCfgFile(err error) error {
	return fmt.Errorf("%w: %s", errCfgFileRead, err.Error())
}

func errReadingDefaultCfgFile(err error) error {
	return fmt.Errorf("%w: %s", errDefaultCfgFileRead, err.Error())
}

func errReadingDotGithubDir(err error) error {
	return fmt.Errorf("%w: %s", errDotGithubDirRead, err.Error())
}

func errReadingDotGithubVarsFile(err error) error {
	return fmt.Errorf("%w: %s", errDotGithubVarsFileRead, err.Error())
}

func errReadingDotGithubSecretsFile(err error) error {
	return fmt.Errorf("%w: %s", errDotGithubSecretsFileRead, err.Error())
}

func main() {
	rootCmd := &cobra.Command{
		Use:   "octo-linter",
		Short: "Validates GitHub Actions workflow and action YAML files",
	}

	rootCmd.AddCommand(createInitCommand())
	rootCmd.AddCommand(createLintCommand())
	rootCmd.AddCommand(&cobra.Command{
		Use:   "version",
		Short: "Prints the current version of the tool",
		Run: func(cmd *cobra.Command, args []string) {
			os.Exit(versionHandler(context.Background()))
		},
	})

	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func createLintCommand() *cobra.Command {
	var path, config, loglevel, varsFile, secretsFile, output string
	var logmultiline bool
	var outputErrors int

	cmd := &cobra.Command{
		Use:   "lint",
		Short: "Runs the linter on files from a specific directory",
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if _, err := os.Stat(path); os.IsNotExist(err) {
				return fmt.Errorf("path '%s' does not exist or is not a directory", path)
			}
			if config != "" {
				if _, err := os.Stat(config); os.IsNotExist(err) {
					return fmt.Errorf("config file '%s' does not exist", config)
				}
			}
			if varsFile != "" {
				if _, err := os.Stat(varsFile); os.IsNotExist(err) {
					return fmt.Errorf("vars-file '%s' does not exist", varsFile)
				}
			}
			if secretsFile != "" {
				if _, err := os.Stat(secretsFile); os.IsNotExist(err) {
					return fmt.Errorf("secrets-file '%s' does not exist", secretsFile)
				}
			}
			if output != "" {
				fileInfo, err := os.Stat(output)
				if os.IsNotExist(err) || !fileInfo.IsDir() {
					return fmt.Errorf("output '%s' does not exist or is not a directory", output)
				}
			}
			return nil
		},
		Run: func(cmd *cobra.Command, args []string) {
			os.Exit(lintHandler(cmd.Context(), loglevel, logmultiline, path, config, varsFile, secretsFile, output, outputErrors))
		},
	}

	cmd.Flags().StringVarP(&path, "path", "p", "", "Path to .github directory (required)")
	cmd.MarkFlagRequired("path")
	cmd.Flags().StringVarP(&config, "config", "c", "", "Linter config with rules in YAML format")
	cmd.Flags().StringVarP(&loglevel, "loglevel", "l", "", "One of INFO, ERR, WARN, DEBUG")
	cmd.Flags().BoolVarP(&logmultiline, "logmultiline", "m", false, "Each log entry key in a separate line")
	cmd.Flags().StringVarP(&varsFile, "vars-file", "z", "", "Check if variable names exist in this file (one per line)")
	cmd.Flags().StringVarP(&secretsFile, "secrets-file", "s", "", "Check if secret names exist in this file (one per line)")
	cmd.Flags().StringVarP(&output, "output", "o", "", "Path to where summary markdown gets generated")
	cmd.Flags().IntVarP(&outputErrors, "output-errors", "u", 0, "Limit numbers of errors shown in the markdown output file")

	return cmd
}

func createInitCommand() *cobra.Command {
	var destination string
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Create sample dotgithub.yml config file",
		Run: func(cmd *cobra.Command, args []string) {
			os.Exit(initHandler(cmd.Context(), destination))
		},
	}

	cmd.Flags().StringVarP(&destination, "destination", "d", "", "Destination filename to write to")
	return cmd
}

func versionHandler(_ context.Context) int {
	_, _ = fmt.Fprintf(os.Stdout, VERSION+"\n")

	return ExitOK
}

func initHandler(_ context.Context, path string) int {
	if path == "" {
		fileInfo, err := os.Stat(configFileName)
		if err != nil && !os.IsNotExist(err) {
			slog.Error(
				"error checking if destination path exists",
				slog.String("destination", configFileName),
				slog.String("err", err.Error()),
			)

			return ExitErrCheckingDstPath
		}

		if err == nil && fileInfo.IsDir() {
			slog.Error(
				"destination file already exists and it is a directory, remove it first or use --destination flag to change"+
					" the destination",
				slog.String("destination", configFileName),
			)

			return ExitDstFileIsDir
		}

		path = configFileName
	}

	err := os.WriteFile(path, linter.GetDefaultConfig(), FileModeDefaultConfig)
	if err != nil {
		slog.Error(
			"error writing default config",
			slog.String("path", path),
			slog.String("err", err.Error()),
		)

		return ExitErrWritingCfg
	}

	slog.Info(
		"Sample configuration file has been created. Run 'lint' command with '-c' flag or put the file in the .github"+
			" directory.",
		slog.String("path", path),
	)

	return ExitOK
}

func lintHandler(ctx context.Context, loglevel string, logmultiline bool, path, config, varsFile, secretsFile, output string, outputErrors int) int {
	setLogger(loglevel, logmultiline)

	lint, err := getLinter(config, path)
	if err != nil && errors.Is(err, errCfgFileGet) {
		return ExitErrGettingCfgFile
	}

	if err != nil && errors.Is(err, errCfgFileRead) {
		return ExitErrReadingCfgFile
	}

	if err != nil && errors.Is(err, errDefaultCfgFileRead) {
		return ExitErrReadingDefaultCfgFile
	}

	dotGithub, err := getDotGithub(
		ctx,
		path,
		varsFile,
		secretsFile,
		lint.Config.Overrides,
	)
	if err != nil && errors.Is(err, errDotGithubDirRead) {
		return ExitErrReadingDotGithubDir
	}

	if err != nil && errors.Is(err, errDotGithubVarsFileRead) {
		return ExitErrReadingVarsFile
	}

	if err != nil && errors.Is(err, errDotGithubSecretsFileRead) {
		return ExitErrReadingSecretsFile
	}

	outputLimit := 0
	if outputErrors > 0 {
		// the cli already validates flag
		outputLimit = outputErrors
	}

	status, err := lint.Lint(dotGithub, output, outputLimit)
	if err != nil {
		slog.Error(
			"error linting",
			slog.String("err", err.Error()),
		)

		return ExitErrLinting
	}

	if status == linter.HasErrors {
		return ExitLintErrors
	}

	if status == linter.HasOnlyWarnings {
		return ExitLintOnlyWarnings
	}

	return 0
}

func getConfigFilePath(filePath string, dotGitHubPath string) (string, error) {
	if filePath != "" {
		return filePath, nil
	}

	configInDotGithub := filepath.Join(dotGitHubPath, configFileName)
	_, err := os.Stat(configInDotGithub)

	notFound := os.IsNotExist(err)
	if err != nil && !notFound {
		slog.Error(
			"error getting config file",
			slog.String("err", err.Error()),
		)

		return "", fmt.Errorf(
			"error getting os.Stat on %s inside .github path: %w",
			configFileName,
			err,
		)
	}

	if notFound {
		return "", nil
	}

	return configInDotGithub, nil
}

func populateConfigFromFile(cfg *linter.Config, cfgFile string) error {
	if cfgFile != "" {
		err := cfg.ReadFile(cfgFile)
		if err != nil {
			slog.Error(
				"error reading config file",
				slog.String("path", cfgFile),
				slog.String("err", err.Error()),
			)

			return errReadingCfgFile(err)
		}
	} else {
		err := cfg.ReadDefaultFile()
		if err != nil {
			slog.Error(
				"error reading default config file",
				slog.String("err", err.Error()),
			)

			return errReadingDefaultCfgFile(err)
		}
	}

	return nil
}

func getLinter(cfgPath string, dotGithubPath string) (*linter.Linter, error) {
	cfgFile, err := getConfigFilePath(cfgPath, dotGithubPath)
	if err != nil {
		return nil, errGettingCfgFile(err)
	}

	configInstance := linter.Config{}

	err = populateConfigFromFile(&configInstance, cfgFile)
	if err != nil {
		return nil, errPopulatingCfgFile(err)
	}

	linterInstance := &linter.Linter{
		Config: &configInstance,
	}

	return linterInstance, nil
}

func getDotGithub(
	ctx context.Context,
	dotGithubPath string,
	varsFile string,
	secretsFile string,
	overrides *linter.Overrides,
) (*dotgithub.DotGithub, error) {
	dotGithub := dotgithub.DotGithub{}

	overridePaths := map[string]string{}
	overrideOutputs := map[string][]*regexp.Regexp{}

	if overrides != nil {
		if len(overrides.ExternalActionsPaths) > 0 {
			for action, path := range overrides.ExternalActionsPaths {
				overridePaths[action] = path
			}
		}
		if len(overrides.ExternalActionsOutputs) > 0 {
			overrideOutputs = overrides.ExternalActionsOutputs
		}
	}

	err := dotGithub.ReadDir(ctx, dotGithubPath, overridePaths, overrideOutputs)
	if err != nil {
		slog.Error(
			"error initializing",
			slog.String("path", dotGithubPath),
			slog.String("err", err.Error()),
		)

		return nil, errReadingDotGithubDir(err)
	}

	if varsFile != "" {
		err = dotGithub.ReadVars(varsFile)
		if err != nil {
			slog.Error(
				"error reading vars file",
				slog.String("path", varsFile),
				slog.String("err", err.Error()),
			)

			return nil, errReadingDotGithubVarsFile(err)
		}
	}

	if secretsFile != "" {
		err = dotGithub.ReadSecrets(secretsFile)
		if err != nil {
			slog.Error(
				"error reading secrets file",
				slog.String("path", secretsFile),
				slog.String("err", err.Error()),
			)

			return nil, errReadingDotGithubSecretsFile(err)
		}
	}

	return &dotGithub, nil
}

func setLogger(loglevelFlag string, multiline bool) {
	logLevel := loglevel.GetLogLevelFromString(loglevelFlag)

	opts := &slog.HandlerOptions{
		Level: logLevel,
		ReplaceAttr: func(groups []string, a slog.Attr) slog.Attr {
			if a.Key == slog.TimeKey {
				return slog.Attr{}
			}
			return a
		},
	}

	var logger *slog.Logger
	if multiline {
		logger = slog.New(&customHandler{opts: opts})
	} else {
		logger = slog.New(slog.NewTextHandler(os.Stderr, opts))
	}

	slog.SetDefault(logger)
}
