name: Test build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    
jobs:
  main:
    name: Build and run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate code
        run: |
          cd cmd/octo-linter
          go generate

      - name: Run tests
        run: |
          go test ./... -v -count=1

      - name: Check if binary builds
        run: |
          cd cmd/octo-linter
          go build .

      - name: Run against test directory
        run: |
          set +e
          cmd/octo-linter/octo-linter lint -p tests/rules
          if [[ $? != 1 ]]; then
            echo "!!! octo-linter should return exit code different than 0"
            exit 1
          fi

          found_errs_in_valid=$(cmd/octo-linter/octo-linter lint -p ../../tests/rules 2>&1 | grep "'valid-workflow\|'valid-action" | wc -l)
          if [[ $found_errs_in_valid != 0 ]]; then
            echo "!!! octo-linter should not find errors on valid workflows"
            exit 1
          fi

          cmd/octo-linter/octo-linter lint -p tests/all-valid
          if [[ $? != 0 ]]; then
            echo "!!! octo-linter should return exit code 0 for valid .github directory"
            exit 1
          fi
          set -e
