name: Test build

on:
  pull_request:
    branches:
      - main
    
jobs:
  main:
    name: Build and run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate code
        run: |
          cd cmd/octo-linter
          go generate

      - name: Run tests
        run: |
          go test ./...

      - name: Check if binary builds
        run: |
          cd cmd/octo-linter
          go build .

